### ISSUE TITLE
Content Staging

### ISSUE THREAD

**Issue by nibra** [joomla-projects/joomla-pythagoras#43]
This can be implemented using the Versioning feature –by tagging versions as "staged"– and a content plugin which on-the-fly replaces the HTML of an item with the staged version. The content plugin is only enabled when a session variable is set and you have the adequate ACL permissions. So this requires a small module (of a similar concept as the language flags module) with a LIVE / STAGING toggle switch.

The only thing I cannot tell you is how the editor page should look like for defining whether you are editing live or staged content.

Please note that this feature does NOT cover staging all data, just versioned items. This means that any data modification such as creating users, making transactions etc have effect on the live version of the site as well. If you need absolute separation you still have to create a clone of your site like you've been doing since Joomla! 1.0.

A rough time budget for this feature is 36 man-hours.

**Comment by nikosdion** [comment]
This can be implemented using the Versioning feature –by tagging versions as "staged"– and a content plugin which on-the-fly replaces the HTML of an item with the staged version. The content plugin is only enabled when a session variable is set and you have the adequate ACL permissions. So this requires a small module (of a similar concept as the language flags module) with a LIVE / STAGING toggle switch.

The only thing I cannot tell you is how the editor page should look like for defining whether you are editing live or staged content.

Please note that this feature does NOT cover staging all data, just versioned items. This means that any data modification such as creating users, making transactions etc have effect on the live version of the site as well. If you need absolute separation you still have to create a clone of your site like you've been doing since Joomla! 1.0.

A rough time budget for this feature is 36 man-hours.

**Comment by laoneo** [comment]
This feature is planed on Joomla 3 in a GSoC project https://summerofcode.withgoogle.com/projects/#5268339920207872. Repository can be found here https://github.com/joomla-projects/gsoc16_shareable-draft-content.
