### ISSUE TITLE
Status of beez3 in Joomla 4?

### ISSUE THREAD

**Issue by zero-24** [joomla-projects/joomla-pythagoras#68]
Should beez3 removed as well as hathor or stay in joomla 4?

**Comment by mbabker** [comment]
I don't think either frontend template stays in J4.  The question really should be whether we ship multiple templates or not.

Hathor's already on the dump list since it's essentially been broken since 3.0 released and is actually less accessible (from what I've heard) than Isis is now.

**Comment by zero-24** [comment]
So there is currently no decision on that? beez3 is mostly broken as well ;)

**Comment by mbabker** [comment]
Hathor was pretty much a "just do it" pull request.  I'm not so sure if anyone's discussed front-end templates but at this point I'd assume that Beez3 and Protostar (and even Isis) won't be present in any form once v4 starts taking shape.

**Comment by zero-24** [comment]
ok so the J4 team let us know if there is the time to do that pulls ;)

**Comment by nikosdion** [comment]
If half of what we discussed in the sprint is implemented neither Protostar nor Beez3 will make any sense. We'll need a different kind of template.

As for the back-end template I suspect we'll have to refactor it, not start from scratch. It depends on what the UX team comes up with in the following months.

**Comment by nibra** [comment]
The current templates will have to work using the LegacyRenderer (don't know yet how, but the 'little pain' paradigma demands it).

However, they will surely not be shipped with 4.0.

**Comment by nikosdion** [comment]
I am mostly worried about how the legacy main content + module positions will translate into the "bento box" paradigm of the page builder. Programmatically it can be mapped by assigning an ad hoc name to the main content area but that will most definitely break the intuitive page builder since what you see is not what you get. Of course this depends on how deep we can go in the first iteration of the page builder. Lots of conditionals here :p

I trust that you'll find a way to maintain a modicum of b/c for templates and extensions. We definitely must work with the marketing team to manage the expectations of our users :)
